export const FETCH_PRODUCTS_SUCCESS = 'FETCH_PRODUCTS_SUCCESS';
export const CART_ITEM_REMOVED = 'CART_ITEM_REMOVED';
export const ADD_TO_CART = 'ADD_TO_CART';
export const CART_PRODUCT_QTY_UPDATED = 'CART_PRODUCT_QTY_UPDATED';
export const CART_CLEARED = 'CART_CLEARED';